# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: mysql:8
    restart: always
    container_name: integration-tests-prisma
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tests
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']